#+title: Bus
* Intro
- Note taken on [2023-06-19 Mon 00:13] \\
  Some of the chapter is marked with (zan ding) it means the translation of the name is a temporary one.

Bus is not difficult. Here is the table of contents: 

1. The Basic Concepts about Bus
2. The Classification and Parameters
3. The Structure of Bus and Bus Protocol
4. The Aribitration and Communication of Bus

This note is arranged differently from Tang's Garbage Book. You should be aware of it.


* The Basic Concept about Bus

** The Concept

The components of the computer system (which are processor, cache, memory, I/O device, external memory) are connected to each other by the means of linking the data line (or the control line, something like that) to the bus. 

Anyway, if there is picture you should understand it well.

You can check the book for more information. (I just don't wanna copy them you know. Tang is not writing wrong this time).

* The Classification and Parameters

** The classification 
- Note taken on [2023-06-18 Sun 22:22] \\
  You should also notice that the classfication is not strictly right. Don't be too yuanjiao zhuyi.

The section is very absurd here. It doesn't tell the how bus is categorized but tells about how it is composed.

Anyway, let us just focus on what Tang said. You should just have a look. There are two kinds of the buses: 
1. *System Bus*, which is composed by
   1. Data Bus
   2. Address Bus
   3. Control Bus
2. *Communication Bus*: This one is shit.

*** System Bus

The system bus is the *biggest* bus, which connects all the parts of the computer together, that is, for example, if processor and memory wants to communicate with each other, that is they want to exchange some blocks of data with each other, the address and the data are transferred to bus and then transferred to the relative part.

You may see the very picture on CSAPP where the intro chapter outlined the computer system; it tells about the system bus.

Moreover the system bus usually have three components: *1. Data Bus; 2. Address Bus; 3. Control Bus.*
Data Bus is used to transfer data. It is usually like a word wide that is 32-bit wide (or it can be 16-bit wide idk). Address Bus  is for address, as the name has suggested. Control bus is used to transfer some control signal. For example the clock pulse and the write enable signal and read enable signal.

*** Communication Bus (zan ding)

This section is shit. According to Tang: 
#+begin_quote
The type of the bus is used for the communication among computer systems or between a computer system and other system.
#+end_quote
Tang wanted to talk about something, but she did not know what is called, so she just faked one.

Absolutely shit. You should just remember that the communication bus is the wire for transferring data between long distance. There are two strategies: 1. serial; 2. parrallel.

Things are easy here.

* The Structure of Bus and Bus Protocol

** The structure of Bus

The structure of Bus actually tells a general principle of the design of the bus, that is, *if two parts with different speed are connected directly, the performance of the high-speed one is slowed down*. Idk why it is right, but it seems right. 

The principle tells us about the structure of the bus. *You should connect the parts with the same speed to the same bus*. For example, there are many types of I/O devices, some of then are high-speed and some of them are low-speed. The PCI *protocol* implements a high-speed bus for internet connection and multi-media devices and a extensible bus for FAX or something like that.

Here comes the protocol. Idk what protocol is either. But you can just leave it for now.

** TODO Multi-bus and Examples

This part sucks. I don't wanna take note about it.

** TODO Bus Protocol

* The Arbitration and Communication of Bus

** TODO The Arbitration

The arbitration is about how to manage the priority of the request of the I/O devices.

** TODO Bus Communication Control (zan ding)

The Bus Communication Control main solve the problem how two part communicate (that is how they exchange blocks of data). 

This section is copied from Stallings' book, where the section is called the /Timing/ of the Bus, where the read and write operations are just examples for better reading. Maybe, you should consider just reading Stallings instead of reading Tang's shitty book.

*** Synchronous Timing

*** Asynchronous Timing

*** Half-Synchronous Timing
