#+title: I/O

In the intro, I will present you the main idea of the chapter and then give you the table of contents.

Table of contents: 
1. The Introduction to I/O (the history of I/O systems and some basic concepts)
2. Some I/O Devices
3. The I/O interfaces
4. 程序查询方式
5. 程序中断方式
6. DMA

Note: Don't be panic when read the section one. It mainly tells us about some basic concepts. You can just skim through the text and acquire some minimun of the knowledge (that would be OK)

Note: Don't read the second section. It sucks.

Yet Another Note: Last three sections are important. Huge amount of contents.

This intro is also needed to be updated.

* The Introduction to I/O

** The History of I/O
- /Interface, channel/ Ishall put the informative description of the two concepts here.

This section first looks at the earlies I/O system structure. Then the section continue to the modern I/O system.

** TODO The elements of I/O [0%]
- [ ]
- [ ]
- [ ]

*** Software (instructure)
*** 联系方式
*** 信息传送方式

* DONE I/O Devices
CLOSED: [2023-06-19 Mon 04:15]

- State "DONE"       from "TODO"       [2023-06-19 Mon 04:15]
This introduces many things, but none of them is useful. You can read this chapter if you found them interesting.

* TODO I/O Interfaces

This one is rather easy.

* TODO 程序查询方式

* TODO 程序中断方式
* TODO DMA
